Navbar
Leoasa1/hotel-frontend pull request #4
Opened 2022-08-16 22:41 UTC by Kqyang29

2022-08-17 06:11 UTC, Leoasa1 requested changes

2022-08-17 06:11 UTC, Leoasa1 commented on components/navbar/Navbar.js
> +		<footer className="inter bg-primary">
Use navbar tag instead of footer tag

2022-08-17 07:46 UTC, Kqyang29 commented on components/navbar/Navbar.js
> +		<footer className="inter bg-primary">
fix！

2022-08-19 00:25 UTC, Leoasa1 approved these changes

2022-08-19 00:25 UTC, merged